name: CI

on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: '27 3,9,15,21 * * *'

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: |
          wget https://github.com/gohugoio/hugo/releases/download/v0.87.0/hugo_extended_0.87.0_Linux-64bit.deb
          sudo dpkg -i hugo*.deb
      - run: |
          wget https://github.com/stedolan/jq/releases/download/jq-1.6/jq-linux64
          sudo mv jq-linux64 /usr/local/bin/jq
      - run: ./ci.sh
